In [45]:
import pandas as pd
import numpy as np
import scipy as sci
import math
import time
from tools.auxiliary import*


df =reading("epsi10000.csv")



In [46]:
df.head()

epsi10000
0  1.261936674008641734e+00
1                  -1.39991
2                 -0.684871
3                  -1.31643
4                  0.358235

In [49]:
df.iloc[0,0]

'1.261936674008641734e+00'

In [107]:
T  = 10000           #Choose the simulation length for the solution procedure, T<=10,000                    
gam     = 1        # Utility-function parameter
alpha   = 0.36     # Capital share in output
beta    = 0.99     # Discount factor
delta   = 0.02     # Depreciation rate 
rho     = 0.95     # Persistence of the log of the productivity level
sigma   = 0.01    # Standard deviation of shocks to the log of the productivity level
ks = ( (1-beta+beta*delta) / (alpha*beta) )**(1/(alpha-1) )

#4. Initial condition
k = np.array([ks]*(T+1))
a= [1]*(T)
# maybe add generation of epsi1000 if got time
epsi = df.iloc[:,0].astype(float)*sigma
epsi=epsi.tolist()

for i in range(1, T):
    a[i]=a[i-1]**(rho)*math.exp(epsi[i])
    


#start = time.time()

#end = time.time()
#duration= (end - start)

##6. The GSSA parameters  
kdamp = 0.01    # Damping parameter for (fixed-point) iteration on 
                      # the coefficients of the capital policy function
dif_GSSA_1d = 1e+10  # Set the initial difference between the series from
                      # two iterations in the convergence criterion (condition
                      # (10) in JMM, 2011) to a very large number
#Initialize the first-degree capital policy function
bk_1d  = np.array([0, 0.95, ks*0.05])
bk_1d= np.reshape(bk_1d, (3,1))
#8. Initialize the capital series
k_old = [ks+1]*(T+1)


In [51]:
dif_GSSA_1d = 1e+10

In [34]:
while dif_GSSA_1d > 1e-4*kdamp:
    x=[[1, k[i], a[i]] for i in range (0,T)]
    x=np.asarray(x)
    for i in range(0,T):
        k[i+1]=np.matmul(x[i], bk_1d).astype(float)
    

In [110]:
#await translation:

c    = k(1:T,1).^alpha.*a(1:T,1)  + (1-delta)*k(1:T,1)-k(2:T+1,1);  
y    =  beta*c(2:T,1).^(-gam)./c(1:T-1,1).^(-gam).*(1-delta+alpha*k(2:T,1).^(alpha-1).*a(2:T,1)).*k(2:T,1);
    dif_GSSA_1d = mean(abs(1-k./k_old))
                   % Compute a unit-free difference between the series from
                   % two iterations; see condition (10) in JMM (2011)
                                 
                                 
    % 9.4 Compute and update the coefficients of the capital policy function
    % ----------------------------------------------------------------------
    bk_hat_1d = inv(x(1:T-1,:)'*x(1:T-1,:))*x(1:T-1,:)'*y(1:T-1,:);
                                 % Compute new coefficients of the capital 
                                 % policy function using the OLS
    bk_1d = kdamp*bk_hat_1d + (1-kdamp)*bk_1d;  
                                 % Update the coefficients of the capital  
                                 % policy function using damping
                                     
    % 9.5 Store the capital series 
    %-----------------------------
    k_old = k; 

array([48.29917764,  0.        , 48.29917764, ..., 48.29917764,
       48.29917764, 48.29917764])

In [121]:

for i in range(0,T):
    k[i+1]=np.matmul(x[i], bk_1d).astype(float)


In [122]:
k

array([48.29917764, 48.29917764, 48.26560604, ..., 48.15782297,
       48.18513516, 48.17346977])

In [119]:
np.matmul(x[i], bk_1d).tolist()

[48.29917764394355]

In [78]:
bk_1d= np.reshape(bk_1d, (3,1))

In [92]:
kkk=np.array([1,2,3,4,5])

In [94]:
k[]=

In [97]:
kkk

array([  1,   2, 100,   4,   5])